# Generated by Django 3.0.5 on 2020-05-04 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parseapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='phno',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
