# Generated by Django 3.0.5 on 2020-05-04 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parseapp', '0002_details_phno'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='pincode',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='details',
            name='st',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
